image: r.cfcr.io/guysaltoncf/codefreshplugins/cfstep-codecommit
version: 0.1.0
description: Clone an AWS CodeCommit Git repository
keywords:
  - codecommit
  - git
  - clone
categories:
  - GIT
sources:
  - https://github.com/codefresh-contrib/cfstep-codecommit
maintainers: 
  - name: Guy Salton
    email: guy.salton@codefresh.io
icon: aws-codecommit.jpg
envs:
  - name: GIT_USER
    type: required
    description: AWS CodeCommit Git username
  - name: GIT_PASSWORD
    type: required
    description: AWS CodeCommit Git password
